// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2ymqv1xjdQGK5_fCpua44HR1hu9zfBJQ',
    appId: '1:482182042337:web:7035b53badde2354a01da0',
    messagingSenderId: '482182042337',
    projectId: 'travelapp-3ff5a',
    authDomain: 'travelapp-3ff5a.firebaseapp.com',
    storageBucket: 'travelapp-3ff5a.appspot.com',
    measurementId: 'G-PQLWRMWKZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg9uRyMmOVo5ecX6Kqhe-P0Lv5Pdw4SDs',
    appId: '1:482182042337:android:e511ec59911f8f9ea01da0',
    messagingSenderId: '482182042337',
    projectId: 'travelapp-3ff5a',
    storageBucket: 'travelapp-3ff5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqZhhgC6Wb3D6UrWgM1P7-evIu99lykFY',
    appId: '1:482182042337:ios:03ef17009b248c68a01da0',
    messagingSenderId: '482182042337',
    projectId: 'travelapp-3ff5a',
    storageBucket: 'travelapp-3ff5a.appspot.com',
    iosBundleId: 'com.corizoproject.travelapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqZhhgC6Wb3D6UrWgM1P7-evIu99lykFY',
    appId: '1:482182042337:ios:03ef17009b248c68a01da0',
    messagingSenderId: '482182042337',
    projectId: 'travelapp-3ff5a',
    storageBucket: 'travelapp-3ff5a.appspot.com',
    iosBundleId: 'com.corizoproject.travelapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2ymqv1xjdQGK5_fCpua44HR1hu9zfBJQ',
    appId: '1:482182042337:web:3aa8a97669d6708ba01da0',
    messagingSenderId: '482182042337',
    projectId: 'travelapp-3ff5a',
    authDomain: 'travelapp-3ff5a.firebaseapp.com',
    storageBucket: 'travelapp-3ff5a.appspot.com',
    measurementId: 'G-7TC8BE5FYJ',
  );
}
